#!/usr/bin/env sh

./node_modules/.bin/crx pack ./build/chrome --zip-output ./build/packages/chrome.zip -o ./build/packages/chrome.crx
cd ./build/firefox
../../node_modules/.bin/jpm xpi
mv *.xpi ../packages/
